name: "commit-master"

on:
  push:
    branches: 
    - 'master'

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
  CURRENT_DATE: ''
  ipaddr: ${ip_address}
  REGIONID: ${region_id} 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out 
      uses: actions/checkout@v2
        
    - name: Set up JDK 19 for maven build
      uses: actions/setup-java@v1
      with:
        java-version: 18

    # 完成java项目打包
    - name: build maven project
      run: mvn clean -U package -Dmaven.test.skip 

    # 设置 docker 环境
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: "build springcloud demo for linux/amd64,linux/arm64/v8,windows/amd64"
      uses: huaweicloud/swr-multiplatform-build-action@v1.0.0
      with:
        imagetag: swr.cn-north-4.myhuaweicloud.com/hcloudcli/nginx:nginx-12-v1.0.0.1
        platforms: linux/386,linux/amd64,linux/arm/v5,linux/arm/v7,linux/arm64/v8,linux/mips64le,linux/ppc64le,linux/s390x
        uselatestbuildx: false
        push: false
        file: ./dockerfiles/Dockerfile-nginx